[General]
### mixed MecHost ###

cmdenv-autoflush = true

##########################################################
#            Output Format Results                       #
##########################################################
num-rngs = 3
repeat = 1
seed-set = ${repetition}
#resultdir-subdivision = true
output-scalar-file = ${resultdir}/${configname}/${configname}-${iterationvarsf}${repetition}.sca
output-vector-file = ${resultdir}/${configname}/${configname}-${iterationvarsf}${repetition}.vec

**.routingRecorder.enabled = false

#**.avgServedBlocksDl.*.vector-recording = true
#**.avgServedBlocksUl.*.vector-recording = true

**.scalar-recording = true
**.vector-recording = true
#
#**.statistic-recording = false




##########################################################
#            Simulation parameters                       #
##########################################################
debug-on-errors = false
print-undisposed = true

sim-time-limit = 200s
warmup-period = 25s

*.playgroundSizeX = 2500m
*.playgroundSizeY = 2500m
*.playgroundSizeZ = 50m


############### IPv4 configurator config #################
*.configurator.config = xmldoc("./demo.xml")

############# Floorplan definition ##################
**.mobility.constraintAreaMaxX = 2500m
**.mobility.constraintAreaMaxY = 2500m
**.mobility.constraintAreaMinX = 0m
**.mobility.constraintAreaMinY = 0m
**.mobility.constraintAreaMinZ = 0m
**.mobility.constraintAreaMaxZ = 0m

##########################################################
#              NR specific parameters                   #
##########################################################
*.gNodeB*.cellInfo.broadcastMessageInterval = 0.5s
**.fbPeriod = 40tti   # reports CQI every 40ms
**.amcType = "NRAmc"
**.pilotMode = "ROBUST_CQI"
**.targetBler = 0.001
**.blerShift = 5

############### General PHY parameters ##############
### da nr/test_multicarriers
#**.downlink_interference = true
#**.uplink_interference = true
#**.enableHandover = true
#**.fbPeriod = 10tti   # reports CQI every 10ms
#**.targetBler = 0.01
#**.blerShift = 5

# ----------------------------------------------------------------------------- #
# Config "SingleMobileMec"
#
[Config SingleMobileMec]
network = simu5g.simulations.NR.mec.mixedMecHost.mixedMecHost

#######################################################
#        CA and channel model configuration           #
#######################################################
*.carrierAggregation.numComponentCarriers = 1
*.carrierAggregation.componentCarrier[0].numBands =  50 #${numBands=25}

*.*.cellularNic.LteChannelModelType = "NRChannelModel"
*.gNodeB1.cellularNic.numCarriers = 1
*.gNodeB1.cellularNic.channelModel[0].componentCarrierModule = "carrierAggregation.componentCarrier[0]"

*.ue[*].cellularNic.numCarriers = 1
*.ue[*].cellularNic.nrChannelModel[0].componentCarrierModule = "carrierAggregation.componentCarrier[0]"

*.mobileMecHost.cellularNic.numCarriers = 1
*.mobileMecHost.cellularNic.nrChannelModel[0].componentCarrierModule = "carrierAggregation.componentCarrier[0]"


##########################################################
#                      Mobility                          #
##########################################################
**.mobility.constraintAreaMinZ = 0m
**.mobility.constraintAreaMaxZ = 0m

*.ue[*].mobility.initFromDisplayString = false
*.ue[*].mobility.typename = "LinearMobility"
*.ue[*].mobility.updateInterval = 0.05s

*.gNodeB1.mobility.initFromDisplayString = true

**.numUes = 3
**.ue[0].mobility.initialX = 180m
**.ue[0].mobility.initialY = 50m
**.ue[0].mobility.initialMovementHeading = 90deg
**.ue[0].mobility.speed = 10mps

**.ue[1].mobility.initialX = 180m
**.ue[1].mobility.initialY = 100m
**.ue[1].mobility.initialMovementHeading = 90deg
**.ue[1].mobility.speed = 10mps

**.ue[2].mobility.initialX = 180m
**.ue[2].mobility.initialY = 150m
**.ue[2].mobility.initialMovementHeading = 90deg
**.ue[2].mobility.speed = 10mps

**.ue[*].masterId = 0
**.ue[*].macCellId = 0
**.ue[*].nrMasterId = 1
**.ue[*].nrMacCellId = 1
**.gNodeB1.macCellId = 1
**.gNodeB1.macNodeId = 1

**.mobileMecHost.masterId = 0
**.mobileMecHost.macCellId = 0
**.mobileMecHost.nrMasterId = 1
**.mobileMecHost.nrMacCellId = 1

**.mobileMecHost.isMobile = true

### Mec Host mobility ###

# RectangleMobility
*.mobileMecHost.mobility.initFromDisplayString = false
*.mobileMecHost.mobility.typename = "RectangleMobility"
*.mobileMecHost.mobility.updateInterval = 0.05s

**.mobileMecHost.mobility.startPos = 0.5
**.mobileMecHost.mobility.speed = 10mps
**.mobileMecHost.mobility.constraintAreaMinX = 475m
**.mobileMecHost.mobility.constraintAreaMinY = 383m
**.mobileMecHost.mobility.constraintAreaMinZ = 0m
**.mobileMecHost.mobility.constraintAreaMaxX = 725m
**.mobileMecHost.mobility.constraintAreaMaxY = 817m
**.mobileMecHost.mobility.constraintAreaMaxZ = 0m

**.hasRNISupport = true

# tcp settings
**.tcp.typename = "Tcp"
**.tcp.advertisedWindow = 65535         # in bytes, corresponds with the maximal receiver buffer capacity (Note: normally, NIC queues should be at least this size)
**.tcp.tcpAlgorithmClass = "TcpReno"    # TcpReno/TcpTahoe/TcpNewReno/TcpNoCongestionControl/DumbTcp
**.tcp.sackSupport = true               # Selective Acknowledgment (RFC 2018, 2883, 3517) support (header option) (SACK will be enabled for a connection if both endpoints support it)

##########################################################
#                    App Layer                           #
##########################################################

#------------UERequestApp---------------
*.ue[*].numApps = 2
*.ue[*].app[0].typename = "DeviceApp"
*.ue[*].app[0].localPort = 4500
*.ue[*].app[0].ualcmpAddress = "ualcmp"
*.ue[*].app[0].ualcmpDestPort = 1000
*.ue[*].app[0].appPackageSource = "ApplicationDescriptors/ResponseCbrApp.json"

*.ue[*].app[1].typename = "UERequestCbrApp"
*.ue[*].app[1].deviceAppAddress = "ue["+string(ancestorIndex(1))+"]"
*.ue[*].app[1].deviceAppPort = 4500
*.ue[*].app[1].startTime = uniform(1s, 5s)	# s(ancestorIndex(1)+0.05) # 										#when sending start request app									#period to sending messages
*.ue[*].app[1].stopTime = 250s										#when sending stop MEC response app
# packet size / send interval
### conf1
*.ue[*].app[1].requestPacketSize = 1000B
*.ue[*].app[1].period = ${sendPeriod=20ms}


### MEC Response App
**.responsePacketSize = 1000B

#----------------------------------------


######################_ME Host Side_#####################
# resources available
*.mecHost.maxMECApps = 100												#max ME Apps to instantiate
*.mecHost.maxRam = 32GB													#max KBytes of Ram Space
*.mecHost.maxDisk = 100TB												#max KBytes of Ram Space
*.mecHost.maxCpuSpeed = 100000											#max percentage of CPU
#----------------------------------------
*.mobileMecHost.maxMECApps = 100										#max ME Apps to instantiate
*.mobileMecHost.maxRam = 32GB											#max KBytes of Ram Space
*.mobileMecHost.maxDisk = 100TB											#max KBytes of Ram Space
*.mobileMecHost.maxCpuSpeed = 100000									#max percentage of CPU
#----------------------------------------

#*.gNodeB*.mecHost = "mecHost"
*.mecHost.bsList = ["gNodeB1"]
*.mecHost.mecPlatformManager.mecOrchestrator = "mecOrchestrator"

*.mobileMecHost.bsList = ["gNodeB1"]
*.mobileMecHost.mecPlatformManager.mecOrchestrator = "mecOrchestrator"


#-------ETSI MEC Services:---------------

### Standard (fixed) MecHosts configuration
*.mecHost.mecPlatform.numMecServices = 1
*.mecHost.mecPlatform.mecService[0].typename = "RNIService"	#"LocationService"
*.mecHost.mecPlatform.mecService[0].localAddress = "mecHost.virtualisationInfrastructure"
*.mecHost.mecPlatform.mecService[0].localPort = 10020

*.mecHost.mecPlatform.mecService[0].rng-0 = 0 # request service time
*.mecHost.mecPlatform.mecService[0].rng-1 = 1 # subscription service time
*.mecHost.mecPlatform.mecService[0].requestServiceTime = 100us	#4ms	#100us
*.mecHost.mecPlatform.mecService[0].subscriptionServiceTime = 11us

*.mecHost.mecPlatform.serviceRegistry.localAddress = "mecHost.virtualisationInfrastructure" #da cambiare!!
*.mecHost.mecPlatform.serviceRegistry.localPort = 10021

*.mecHost.mecPlatform.serviceRegistry.rng-0 = 0 # request service time
*.mecHost.mecPlatform.serviceRegistry.rng-1 = 1 # subscription service time

### Mobile MecHost configuration
*.mobileMecHost.mecPlatform.numMecServices = 1
*.mobileMecHost.mecPlatform.mecService[0].typename = "RNIService"
*.mobileMecHost.mecPlatform.mecService[0].localAddress = "mobileMecHost"
*.mobileMecHost.mecPlatform.mecService[0].localPort = 10020

*.mobileMecHost.mecPlatform.mecService[0].rng-0 = 0 # request service time
*.mobileMecHost.mecPlatform.mecService[0].rng-1 = 1 # subscription service time
*.mobileMecHost.mecPlatform.mecService[0].requestServiceTime = 100us	#4ms	#100us
*.mobileMecHost.mecPlatform.mecService[0].subscriptionServiceTime = 11us

*.mobileMecHost.mecPlatform.serviceRegistry.localAddress = "mobileMecHost"
*.mobileMecHost.mecPlatform.serviceRegistry.localPort = 10021

*.mobileMecHost.mecPlatform.serviceRegistry.rng-0 = 0 # request service time
*.mobileMecHost.mecPlatform.serviceRegistry.rng-1 = 1 # subscription service time


#------- MEC orchestrator---------------
**.mecOrchestrator.mecHostList = ["mecHost", "mobileMecHost"]
**.mecOrchestrator.mecApplicationPackageList = ["ResponseCbrApp"]   # List of MEC app descriptors to be onboarded at
**.mecOrchestrator.selectionPolicy = "AvailableResourcesBased"

# ----------------------------------------------------------------------------- #
# Config "StationaryMobility"
#
# This configuration has one MobileMecHostNode with stationary mobility, close to the gNodeB
# The UEs have random mobility and speed
[Config TuningCbrScenario]
extends = SingleMobileMec

#**.sctp.nagleEnabled = false         # if true, transmission of small packets will be delayed on the X2
#
#**.tcp.nagleEnabled = false

#------------UE config---------------
**.numUes = ${numUEs=45}

*.ue[*].mobility.typename = "RandomWaypointMobility"
*.ue[*].mobility.initFromDisplayString = false

# UE mobility limited in a rectangular area inside the coverage area of the gNodeB
**.ue[*].mobility.constraintAreaMinX = 475m
**.ue[*].mobility.constraintAreaMaxX = 725m
**.ue[*].mobility.constraintAreaMinY = 383m
**.ue[*].mobility.constraintAreaMaxY = 817m
**.ue[*].mobility.constraintAreaMinZ = 0m
**.ue[*].mobility.constraintAreaMaxZ = 100m

#**.ue[0].mobility.initialMovementHeading = 0deg
#**.ue[1].mobility.initialMovementHeading = 180deg
#**.ue[*].mobility.initialMovementHeading = 90deg
#
#**.ue[0].mobility.initialX = 475m
#**.ue[0].mobility.initialY = 383m
#**.ue[1].mobility.initialX = 725m
#**.ue[1].mobility.initialY = 817m
#**.ue[2].mobility.initialX = 725m
#**.ue[2].mobility.initialY = 383m


**.ue[*].mobility.initialX = uniform(this.constraintAreaMinX, this.constraintAreaMaxX)
**.ue[*].mobility.initialY = uniform(this.constraintAreaMinX, this.constraintAreaMaxX)
**.ue[*].mobility.speed = exponential(10mps)

#------------gNodeB config---------------
*.gNodeB1.mobility.initFromDisplayString = false
*.gNodeB1.mobility.initialX = 600m
*.gNodeB1.mobility.initialY = 600m
*.gNodeB1.mobility.initialZ = 0m

*.gNodeB1.cellularNic.bgTrafficGenerator[*].numBgUes = 0

#------------MecHost config---------------
*.mobileMecHost.mobility.initFromDisplayString = false
*.mobileMecHost.mobility.typename = "StationaryMobility"

# mobileMecHost in a fixed position close to the base station
**.mobileMecHost.mobility.initialX = 600m
**.mobileMecHost.mobility.initialY = 650m

#------------CQI-------------
**.useProbabilisticCqi = true

#------------Background Cells config---------------
*.numBgCells = 0	#${numBgCells=0}
*.bgCell[*].mobility.initFromDisplayString = false

*.bgCell[*].bgTrafficGenerator.numBgUes = ${numBgUEs=30}

*.bgCell[0].mobility.initialX = 350m
*.bgCell[0].mobility.initialY = 167m
*.bgCell[1].mobility.initialX = 1100m
*.bgCell[1].mobility.initialY = 600m
*.bgCell[2].mobility.initialX = 350m
*.bgCell[2].mobility.initialY = 1033m

*.bgCell[3].mobility.initialX = 850m
*.bgCell[3].mobility.initialY = 167m
*.bgCell[4].mobility.initialX = 850m
*.bgCell[4].mobility.initialY = 1033m
*.bgCell[5].mobility.initialX = 100m
*.bgCell[5].mobility.initialY = 600m

*.bgCell[*].bgScheduler.isNr = true
*.bgCell[*].bgScheduler.numBands = 50 #${rbs=100}
*.bgCell[*].bgScheduler.numerologyIndex = 0 	# ${u=0}
#*.bgCell[*].bgScheduler.txPower = ${bgTxPwr=23dBm}

# position of background UEs in the background cells
*.bgCell[*].bgTrafficGenerator.bgUE[*].mobility.typename = "RandomWaypointMobility"
*.bgCell[*].bgTrafficGenerator.bgUE[*].mobility.initFromDisplayString = false

**.bgCell[*].bgTrafficGenerator.bgUE[*].mobility.constraintAreaMaxX = 2500m
**.bgCell[*].bgTrafficGenerator.bgUE[*].mobility.constraintAreaMaxY = 2500m
**.bgCell[*].bgTrafficGenerator.bgUE[*].mobility.constraintAreaMinX = -200m
**.bgCell[*].bgTrafficGenerator.bgUE[*].mobility.constraintAreaMinY = -200m

*.bgCell[0].bgTrafficGenerator.bgUE[*].mobility.initialX = uniform(100m,600m)
*.bgCell[0].bgTrafficGenerator.bgUE[*].mobility.initialY = uniform(-83m,417m)
*.bgCell[1].bgTrafficGenerator.bgUE[*].mobility.initialX = uniform(850m,1350m)
*.bgCell[1].bgTrafficGenerator.bgUE[*].mobility.initialY = uniform(350m,850m)
*.bgCell[2].bgTrafficGenerator.bgUE[*].mobility.initialX = uniform(100m,600m)
*.bgCell[2].bgTrafficGenerator.bgUE[*].mobility.initialY = uniform(783m,1233m)

*.bgCell[3].bgTrafficGenerator.bgUE[*].mobility.initialX = uniform(600m,1100m)
*.bgCell[3].bgTrafficGenerator.bgUE[*].mobility.initialY = uniform(-83m,417m)
*.bgCell[4].bgTrafficGenerator.bgUE[*].mobility.initialX = uniform(600m,1100m)
*.bgCell[4].bgTrafficGenerator.bgUE[*].mobility.initialY = uniform(783m,1233m)
*.bgCell[5].bgTrafficGenerator.bgUE[*].mobility.initialX = uniform(-150m,350m)
*.bgCell[5].bgTrafficGenerator.bgUE[*].mobility.initialY = uniform(350m,850m)

*.bgCell[*].bgTrafficGenerator.bgUE[*].mobility.speed = exponential(10mps)

######### CQI and HARQ parameters for background UEs
#include trafficGeneratorConfigs/config-u=0-rbs=100-numBgCells=6-numBkUEs=15-dist=50m-repetition=0.ini

*.bgCell[*].bgTrafficGenerator.bgUE[*].generator.typename = "TrafficGeneratorCbr"
*.bgCell[*].bgTrafficGenerator.bgUE[*].generator.startTimeDl = uniform(0ms, 5ms)
*.bgCell[*].bgTrafficGenerator.bgUE[*].generator.packetSizeDl = 1000B
*.bgCell[*].bgTrafficGenerator.bgUE[*].generator.periodDl = 20ms

*.bgCell[*].bgTrafficGenerator.bgUE[*].generator.startTimeUl = uniform(0ms, 5ms)
*.bgCell[*].bgTrafficGenerator.bgUE[*].generator.packetSizeUl = 1000B
*.bgCell[*].bgTrafficGenerator.bgUE[*].generator.periodUl = 20ms

# ----------------------------------- #
*.bgCell[*].bgTrafficGenerator.bgUE[*].generator.rtxRateDl = 0
*.bgCell[*].bgTrafficGenerator.bgUE[*].generator.rtxRateUl = 0
*.bgCell[*].bgTrafficGenerator.bgUE[*].generator.cqiMeanDl = uniform(5, 13)
*.bgCell[*].bgTrafficGenerator.bgUE[*].generator.cqiStddevDl = 0
*.bgCell[*].bgTrafficGenerator.bgUE[*].generator.cqiMeanUl = uniform(5, 13)
*.bgCell[*].bgTrafficGenerator.bgUE[*].generator.cqiStddevUl = 0
#------------------------------------------------------------------------------#

