[General]
### multiCell_mobileMecHost scenario ###
network = simu5g.simulations.NR.mec.multiCell_mobileMecHost.multiCell_mobileMecHost
cmdenv-autoflush = true

**.routingRecorder.enabled = false

##########################################################
#            Output Format Results                       #
##########################################################
num-rngs = 3
repeat = 1
seed-set = ${repetition}
output-scalar-file = ${resultdir}/${configname}/${configname}-${iterationvarsf}${repetition}.sca
output-vector-file = ${resultdir}/${configname}/${configname}-${iterationvarsf}${repetition}.vec

**.sctp.**.scalar-recording = false  # remove annoying statistics from SCTP
**.sctp.**.vector-recording = false  # remove annoying statistics from SCTP

**.scalar-recording = true
**.vector-recording = true

############### SCTP configuration ##################
**.sctp.nagleEnabled = false         # if true, transmission of small packets will be delayed on the X2
**.sctp.enableHeartbeats = false


##########################################################
#            Simulation parameters                       #
##########################################################
debug-on-errors = false
print-undisposed = true

sim-time-limit = 100s
warmup-period = 0s

*.playgroundSizeX = 2500m
*.playgroundSizeY = 2500m
*.playgroundSizeZ = 50m


############### IPv4 configurator config #################
#**.routingTable.netmaskRoutes = ""
#**.configurator.addSubnetRoutes = false
#**.configurator.addDefaultRoutes = false
*.configurator.config = xmldoc("./demo.xml")
**.configurator.dumpRoutes = true


##########################################################
#              NR specific parameters                   #
##########################################################
############### General PHY parameters ##############
*.gnb*.cellInfo.broadcastMessageInterval = 0.5s
**.fbPeriod = 40tti   # reports CQI every 40ms
**.amcType = "NRAmc"
**.pilotMode = "STDDEV_CQI"
**.targetBler = 0.001
**.blerShift = 5
**.fading = false

#**.downlink_interference = true
#**.uplink_interference = true
#**.ueTxPower = 26dBm
#**.eNodeBTxPower = 46dBm

# ----------------------------------------------------------------------------- #

#######################################################
#        CA and channel model configuration           #
#######################################################
*.carrierAggregation.numComponentCarriers = 1
*.carrierAggregation.componentCarrier[0].carrierFrequency = 2GHz
*.carrierAggregation.componentCarrier[0].numBands = 50
#*.carrierAggregation.componentCarrier[0].numerologyIndex = ${u=0}

*.*.cellularNic.LteChannelModelType = "NRChannelModel"
*.gnb*.cellularNic.numCarriers = 1
*.gnb*.cellularNic.channelModel[0].componentCarrierModule = "carrierAggregation.componentCarrier[0]"

*.ue[*].cellularNic.numCarriers = 1
*.ue[*].cellularNic.nrChannelModel[0].componentCarrierModule = "carrierAggregation.componentCarrier[0]"

*.mobileMecHost.cellularNic.numCarriers = 1
*.mobileMecHost.cellularNic.nrChannelModel[0].componentCarrierModule = "carrierAggregation.componentCarrier[0]"

################# X2 configuration #################
*.gnb2.numX2Apps = 2                                       
*.gnb*.numX2Apps = 1                                        # one x2App per peering node
*.gnb*.x2App[*].server.localPort = 5000 + ancestorIndex(1)  # Server ports (x2App[0]=5000, x2App[1]=5001, ...)

*.gnb1.x2App[0].client.connectAddress = "gnb2%x2ppp0"
*.gnb2.x2App[0].client.connectAddress = "gnb1%x2ppp0"

*.gnb2.x2App[1].client.connectAddress = "gnb3%x2ppp0"
*.gnb3.x2App[0].client.connectAddress = "gnb2%x2ppp1"

############### Internet Cloud configuration ##############

**.internet.ipv4Delayer.rng-0 = 1
**.internet.ipv4Delayer.config = xmldoc("internetCloud.xml")

##########################################################
#                      Mobility                          #
##########################################################
**.mobility.constraintAreaMinZ = 0m
**.mobility.constraintAreaMaxZ = 0m

#------------UE config---------------
*.ue[*].mobility.initFromDisplayString = false
*.ue[*].mobility.typename = "LinearMobility"
*.ue[*].mobility.updateInterval = 0.05s

**.numUes = 1
**.ue[0].mobility.initialX = 150m
**.ue[0].mobility.initialY = 600m
**.ue[0].mobility.initialMovementHeading = 0deg
**.ue[0].mobility.speed = 10mps

**.ue[1].mobility.initialX = 180m
**.ue[1].mobility.initialY = 620m
**.ue[1].mobility.initialMovementHeading = 0deg
**.ue[1].mobility.speed = 10mps

**.ue[*].mobility.initialX = uniform(this.constraintAreaMinX, this.constraintAreaMaxX)
**.ue[*].mobility.initialY = uniform(this.constraintAreaMinX, this.constraintAreaMaxX)
**.ue[*].mobility.speed = exponential(10mps)

**.ue[*].masterId = 0
**.ue[*].macCellId = 0
**.ue[*].nrMasterId = 1
**.ue[*].nrMacCellId = 1
**.dynamicCellAssociation = true
**.enableHandover = true

#------------gNodeB config---------------
*.gnb*.mobility.initFromDisplayString = false

*.gnb1.mobility.initialX = 180m
*.gnb1.mobility.initialY = 450m
*.gnb1.mobility.initialZ = 0m

*.gnb2.mobility.initialX = 680m
*.gnb2.mobility.initialY = 450m
*.gnb2.mobility.initialZ = 0m

*.gnb3.mobility.initialX = 1180m
*.gnb3.mobility.initialY = 450m
*.gnb3.mobility.initialZ = 0m

*.gNodeB1.cellularNic.bgTrafficGenerator[*].numBgUes = 0

**.gnb*.macCellId = 1
**.gnb*.macNodeId = 1

#------------mobileMEcHost config---------------
**.mobileMecHost.masterId = 0
**.mobileMecHost.macCellId = 0
**.mobileMecHost.nrMasterId = 1
**.mobileMecHost.nrMacCellId = 1

**.mobileMecHost.isMobile = true

*.mobileMecHost.mobility.initFromDisplayString = true
*.mobileMecHost.mobility.typename = "StationaryMobility"

**.hasRNISupport = true

# tcp settings
**.tcp.typename = "Tcp"
**.tcp.advertisedWindow = 65535         # in bytes, corresponds with the maximal receiver buffer capacity (Note: normally, NIC queues should be at least this size)
**.tcp.tcpAlgorithmClass = "TcpReno"    # TcpReno/TcpTahoe/TcpNewReno/TcpNoCongestionControl/DumbTcp
**.tcp.sackSupport = true               # Selective Acknowledgment (RFC 2018, 2883, 3517) support (header option) (SACK will be enabled for a connection if both endpoints support it)

##########################################################
#                    App Layer                           #
##########################################################

#########################_UE Side_#######################

#------------UERequestApp---------------
*.ue[*].numApps = 2
*.ue[*].app[0].typename = "DeviceApp"
*.ue[*].app[0].localPort = 4500
*.ue[*].app[0].ualcmpAddress = "ualcmp"
*.ue[*].app[0].ualcmpDestPort = 1000
*.ue[*].app[0].appPackageSource = "ApplicationDescriptors/ResponseCbrApp.json"

*.ue[*].app[1].typename = "UERequestCbrApp"
*.ue[*].app[1].deviceAppAddress = "ue["+string(ancestorIndex(1))+"]"
*.ue[*].app[1].deviceAppPort = 4500
*.ue[*].app[1].startTime = uniform(1s, 5s)										#when sending start request app									#period to sending messages
*.ue[*].app[1].stopTime = 250s

# packet size / send interval
*.ue[*].app[1].requestPacketSize = ${pktSize=500B}
*.ue[*].app[1].period = 20ms

### MEC Response App
**.responsePacketSize = ${pktSize}										#when sending stop MEC response app

#----------------------------------------


######################_ME Host Side_#####################
#**.mecHost*.virtualisationInfrastructure.ipv4.forwarding = true
# resources available
*.mecHost*.maxMECApps = 100												#max ME Apps to instantiate
*.mecHost*.maxRam = 32GB												#max KBytes of Ram Space
*.mecHost*.maxDisk = 100TB												#max KBytes of Ram Space
*.mecHost*.maxCpuSpeed = 400000											#max percentage of CPU
#----------------------------------------
# resources available
*.mobileMecHost.maxMECApps = 100										#max ME Apps to instantiate
*.mobileMecHost.maxRam = 32GB											#max KBytes of Ram Space
*.mobileMecHost.maxDisk = 100TB											#max KBytes of Ram Space
*.mobileMecHost.maxCpuSpeed = 400000									#max percentage of CPU
#----------------------------------------

*.mecHost*.bsList = ["gnb1", "gnb2", "gnb3"]
*.mecHost*.mecPlatformManager.mecOrchestrator = "mecOrchestrator"

*.mobileMecHost.bsList = ["gnb1", "gnb2", "gnb3"]
*.mobileMecHost.mecPlatformManager.mecOrchestrator = "mecOrchestrator"


#-------ETSI MEC Services:---------------





#------- MEC orchestrator---------------
#*.mecOrchestrator.mecHostList = ["mobileMecHost", "mecHost1"]	#"mecHost1", "mecHost2", "mecHost3", 
*.mecOrchestrator.mecApplicationPackageList = ["ResponseCbrApp"]   # List of MEC app descriptors to be onboarded at
#*.mecOrchestrator.selectionPolicy = "AvailableResourcesBased"

# ############################################################################## #

# Config
# Benchmark configuration with a standard mecHost and an UE moving linearly in the network 
# and connecting to different gnb through handover procedure
[Config MobileMecHost_2a]

**.isMobile = false
**.isStatic = true
#------- MEC orchestrator---------------
*.mecOrchestrator.mecHostList = ["mecHost1"]	#"mecHost1", "mecHost2", "mecHost3", 

### Standard (fixed) MecHosts configuration
*.mecHost*.mecPlatform.numMecServices = 1
*.mecHost*.mecPlatform.mecService[0].typename = "RNIService"
*.mecHost1.mecPlatform.mecService[0].localAddress = "mecHost1.virtualisationInfrastructure"
#*.mecHost2.mecPlatform.mecService[0].localAddress = "mecHost2.virtualisationInfrastructure"
#*.mecHost3.mecPlatform.mecService[0].localAddress = "mecHost3.virtualisationInfrastructure"
*.mecHost*.mecPlatform.mecService[0].localPort = 10020
*.mecHost1.mecPlatform.serviceRegistry.localAddress = "mecHost1.virtualisationInfrastructure"
#*.mecHost2.mecPlatform.serviceRegistry.localAddress = "mecHost2.virtualisationInfrastructure"
#*.mecHost3.mecPlatform.serviceRegistry.localAddress = "mecHost3.virtualisationInfrastructure"
*.mecHost*.mecPlatform.serviceRegistry.localPort = 10021

*.mecHost*.mecPlatform.mecService[0].rng-0 = 0 # request service time
*.mecHost*.mecPlatform.mecService[0].rng-1 = 1 # subscription service time
*.mecHost*.mecPlatform.mecService[0].requestServiceTime = 100us
*.mecHost*.mecPlatform.mecService[0].subscriptionServiceTime = 11us

*.mecHost*.mecPlatform.serviceRegistry.rng-0 = 0 # request service time
*.mecHost*.mecPlatform.serviceRegistry.rng-1 = 1 # subscription service time


# ############################################################################## #
# Config 
#
# Configuration with a mobile Mec Host attached to an UE moving linearly in the network

[Config MobileMecHost_2b]

**.isMobile = true
**.isStatic = false
#------- MEC orchestrator---------------
*.mecOrchestrator.mecHostList = ["mobileMecHost"]

*.mobileMecHost.bsList = ["gnb1", "gnb2", "gnb3"]

### Mobile MecHost configuration
*.mobileMecHost.mecPlatform.numMecServices = 1
*.mobileMecHost.mecPlatform.mecService[0].typename = "RNIService"
*.mobileMecHost.mecPlatform.mecService[0].localAddress = "mobileMecHost"
*.mobileMecHost.mecPlatform.mecService[0].localPort = 10020

*.mobileMecHost.mecPlatform.mecService[0].rng-0 = 0 # request service time
*.mobileMecHost.mecPlatform.mecService[0].rng-1 = 1 # subscription service time
*.mobileMecHost.mecPlatform.mecService[0].requestServiceTime = 100us
*.mobileMecHost.mecPlatform.mecService[0].subscriptionServiceTime = 11us

*.mobileMecHost.mecPlatform.serviceRegistry.localAddress = "mobileMecHost"
*.mobileMecHost.mecPlatform.serviceRegistry.localPort = 10021

*.mobileMecHost.mecPlatform.serviceRegistry.rng-0 = 0 # request service time
*.mobileMecHost.mecPlatform.serviceRegistry.rng-1 = 1 # subscription service time

## -----------Mobility---------------

# other hosts are also moving around in a larger circle following host[0]
**.mobileMecHost.mobility.initFromDisplayString = false
**.mobileMecHost.mobility.typename = "AttachedMobility"
**.mobileMecHost.mobility.mobilityModule = "^.^.ue[0].mobility"
**.mobileMecHost.mobility.offsetX = -10m
**.mobileMecHost.mobility.offsetHeading = 45deg

**.mobility.constraintAreaMinX = 0m
**.mobility.constraintAreaMaxX = 2500m
**.mobility.constraintAreaMinY = 0m
**.mobility.constraintAreaMaxY = 2500m

# ############################################################################## #
# Config 
#
# Configuration with a mobile Mec Host and a standard one
# several UE

[Config MobileMecHost_2c]
extends = MobileMecHost_2a, MobileMecHost_2b

**.isMobile = true
**.isStatic = true
#------- MEC orchestrator---------------
*.mecOrchestrator.mecHostList = ["mobileMecHost", "mecHost1"]
*.mecOrchestrator.selectionPolicy = "AvailableResourcesBased"	# todo: change policy


**.numUes = 15

# ----------------------------------------------------------------------------- #
