//
//                  Simu5G
//
//
// This file is part of a software released under the license included in file
// "license.pdf". Please read LICENSE and README files before using it.
// The above files and the present reference are part of the software itself,
// and cannot be removed from it.
//

namespace simu5g;

// Link Directions
enum MecServiceEnum
{
    LS = 0; RNIS = 1; AMS = 2; HMS = 3;
};
