[General]
cmdenv-autoflush = true

##########################################################
#            Output Format Results                       #
##########################################################
num-rngs = 3
repeat = 1
seed-set = ${repetition}
output-scalar-file = ${resultdir}/${configname}/${repetition}.sca
output-vector-file = ${resultdir}/${configname}/${repetition}.vec
**.routingRecorder.enabled = false
**.scalar-recording = false
**.vector-recording = false



##########################################################
#            Simulation parameters                       #
##########################################################
debug-on-errors = false
print-undisposed = true

sim-time-limit = 160s
warmup-period = 10s

*.playgroundSizeX = 1100m
*.playgroundSizeY = 800m
*.playgroundSizeZ = 50m


############### IPv4 configurator config #################
*.configurator.config = xmldoc("./demo.xml")


##########################################################
#              NR specific parameters                   #
##########################################################
*.gnb*.cellInfo.broadcastMessageInterval = 0.5s
**.fbPeriod = 40tti   # reports CQI every 40ms
**.amcType = "NRAmc"
**.pilotMode = "ROBUST_CQI"
**.targetBler = 0.01
**.blerShift = 5

# ----------------------------------------------------------------------------- #
# Configuration with a mobile Mec Host connected all the time to a single gNodeB
# an UE moving linearly in the network
#each gNodeB is also connected to other mecHost "standard"
#
[Config MobileMecHost_2a]
network = simu5g.simulations.NR.mec.dynamicMobileMecHost.DynamicMobileMecHost

#######################################################
#        CA and channel model configuration           #
#######################################################
*.carrierAggregation.numComponentCarriers = 1
*.carrierAggregation.componentCarrier[0].numBands =  25 #${numBands=25}

*.*.cellularNic.LteChannelModelType = "NRChannelModel"
*.gnb*.cellularNic.numCarriers = 1
*.gnb*.cellularNic.channelModel[0].componentCarrierModule = "carrierAggregation.componentCarrier[0]"
*.ue[*].cellularNic.numCarriers = 1
*.ue[*].cellularNic.nrChannelModel[0].componentCarrierModule = "carrierAggregation.componentCarrier[0]"

*.mobileMecHost.cellularNic.numCarriers = 1
*.mobileMecHost.cellularNic.nrChannelModel[0].componentCarrierModule = "carrierAggregation.componentCarrier[0]"


##########################################################
#                      Mobility                          #
##########################################################
**.mobility.constraintAreaMinZ = 0m
**.mobility.constraintAreaMaxZ = 0m

*.ue[*].mobility.initFromDisplayString = false
*.ue[*].mobility.typename = "LinearMobility"
*.ue[*].mobility.updateInterval = 0.05s

*.gnb*.mobility.initFromDisplayString = true

#**.numUes = 3
**.ue[0].mobility.initialX = 280m
**.ue[0].mobility.initialY = 600m
**.ue[0].mobility.initialMovementHeading = 0deg
**.ue[0].mobility.speed = 10mps

**.ue[*].masterId = 0
**.ue[*].macCellId = 0
**.ue[*].nrMasterId = 1
**.ue[*].nrMacCellId = 1
**.gnb*.macCellId = 1
**.gnb*.macNodeId = 1

**.mobileMecHost.masterId = 0
**.mobileMecHost.macCellId = 0
**.mobileMecHost.nrMasterId = 1
**.mobileMecHost.nrMacCellId = 1

#**.gnb*.isMobile = true
**.mobileMecHost.isMobile = true

# Mec Host mobility

*.mecHost.mobility.initFromDisplayString = true
*.mecHost.mobility.typename = "StationaryMobility"

#
#**.mecHost.mobility.constraintAreaMinX = 100m
#**.mecHost.mobility.constraintAreaMinY = 100m
#**.mecHost.mobility.constraintAreaMinZ = 0m
#**.mecHost.mobility.constraintAreaMaxX = 500m
#**.mecHost.mobility.constraintAreaMaxY = 300m
#**.mecHost.mobility.constraintAreaMaxZ = 0m

**.hasRNISupport = true

# tcp settings
**.tcp.typename = "Tcp"
**.tcp.advertisedWindow = 65535         # in bytes, corresponds with the maximal receiver buffer capacity (Note: normally, NIC queues should be at least this size)
**.tcp.tcpAlgorithmClass = "TcpReno"    # TcpReno/TcpTahoe/TcpNewReno/TcpNoCongestionControl/DumbTcp
**.tcp.sackSupport = true               # Selective Acknowledgment (RFC 2018, 2883, 3517) support (header option) (SACK will be enabled for a connection if both endpoints support it)

##########################################################
#                    App Layer                           #
##########################################################

#########################_UE Side_#######################

#------------UERequestApp---------------
*.ue[*].numApps = 2
*.ue[*].app[0].typename = "DeviceApp"
*.ue[*].app[0].localPort = 4500
*.ue[*].app[0].ualcmpAddress = "ualcmp"
*.ue[*].app[0].ualcmpDestPort = 1000
*.ue[*].app[0].appPackageSource = "ApplicationDescriptors/ResponseApp.json"

*.ue[*].app[1].typename = "UERequestApp"
*.ue[*].app[1].deviceAppAddress = "ue["+string(ancestorIndex(1))+"]"
*.ue[*].app[1].deviceAppPort = 4500
*.ue[*].app[1].startTime = 5s										#when sending start request app									#period to sending messages
*.ue[*].app[1].stopTime = 190s										#when sending stop MEC response app

#----------------------------------------


######################_ME Host Side_#####################
# resources available
*.mecHost*.maxMECApps = 100												#max ME Apps to instantiate
*.mecHost*.maxRam = 32GB													#max KBytes of Ram Space
*.mecHost*.maxDisk = 100TB												#max KBytes of Ram Space
*.mecHost*.maxCpuSpeed = 400000											#max percentage of CPU
#----------------------------------------
# resources available
*.mobileMecHost.maxMECApps = 100												#max ME Apps to instantiate
*.mobileMecHost.maxRam = 32GB													#max KBytes of Ram Space
*.mobileMecHost.maxDisk = 100TB												#max KBytes of Ram Space
*.mobileMecHost.maxCpuSpeed = 400000											#max percentage of CPU
#----------------------------------------

#*.gNodeB*.mecHost = "mecHost"
*.mecHost*.bsList = ["gnb1", "gnb2", "gnb3"]
*.mecHost*.mecPlatformManager.mecOrchestrator = "mecOrchestrator"

*.mobileMecHost.bsList = ["gnb1"]
*.mobileMecHost.mecPlatformManager.mecOrchestrator = "mecOrchestrator"


#-------ETSI MEC Services:---------------

# MecHosts stationary
*.mecHost*.mecPlatform.numMecServices = 1
*.mecHost*.mecPlatform.mecService[0].typename = "RNIService"
*.mecHost1.mecPlatform.mecService[0].localAddress = "mecHost1.virtualisationInfrastructure"
*.mecHost2.mecPlatform.mecService[0].localAddress = "mecHost2.virtualisationInfrastructure"
*.mecHost3.mecPlatform.mecService[0].localAddress = "mecHost3.virtualisationInfrastructure"
*.mecHost*.mecPlatform.mecService[0].localPort = 10020
*.mecHost1.mecPlatform.serviceRegistry.localAddress = "mecHost1.virtualisationInfrastructure"
*.mecHost2.mecPlatform.serviceRegistry.localAddress = "mecHost2.virtualisationInfrastructure"
*.mecHost3.mecPlatform.serviceRegistry.localAddress = "mecHost3.virtualisationInfrastructure"
*.mecHost*.mecPlatform.serviceRegistry.localPort = 10021

*.mecHost*.mecPlatform.mecService[0].rng-0 = 0 # request service time
*.mecHost*.mecPlatform.mecService[0].rng-1 = 1 # subscription service time
*.mecHost*.mecPlatform.mecService[0].requestServiceTime = 4ms	#100us
*.mecHost*.mecPlatform.mecService[0].subscriptionServiceTime = 11us

*.mecHost*.mecPlatform.serviceRegistry.rng-0 = 0 # request service time
*.mecHost*.mecPlatform.serviceRegistry.rng-1 = 1 # subscription service time

# Mobile MecHost configuration
*.mobileMecHost.mecPlatform.numMecServices = 1
*.mobileMecHost.mecPlatform.mecService[0].typename = "RNIService"
*.mobileMecHost.mecPlatform.mecService[0].localAddress = "mobileMecHost"
*.mobileMecHost.mecPlatform.mecService[0].localPort = 10020
*.mobileMecHost.mecPlatform.serviceRegistry.localAddress = "mobileMecHost"
*.mobileMecHost.mecPlatform.serviceRegistry.localPort = 10021


#------- MEC orchestrator---------------
*.mecOrchestrator.mecHostList = ["mecHost1", "mecHost2", "mecHost3", "mobileMecHost"]
*.mecOrchestrator.mecApplicationPackageList = ["ResponseApp"]   # List of MEC app descriptors to be onboarded at


# ----------------------------------------------------------------------------- #
# Config "StationaryMobility"
#
# This configuration has one MobileMecHostNode with stationary mobility, close to the gNodeB
# The UEs have random mobility and speed
[Config MobileMecHost_2b]
extends = MobileMecHost_2a


*.mobileMecHost.bsList = ["gnb1", "gnb2", "gnb3"]

## -----------Mobility---------------

# other hosts are also moving around in a larger circle following host[0]
**.mobileMecHost.mobility.typename = "AttachedMobility"
**.mobileMecHost.mobility.mobilityModule = "^.^.ue[0].mobility"
**.mobileMecHost.mobility.offsetX = -50m
**.mobileMecHost.mobility.offsetHeading = 0deg

**.mobility.constraintAreaMinX = 0m
**.mobility.constraintAreaMaxX = 800m
**.mobility.constraintAreaMinY = 0m
**.mobility.constraintAreaMaxY = 800m

#------------UE config---------------
**.numUes = intuniform(3, 30)

*.ue[*].mobility.typename = "RandomWaypointMobility"
*.ue[*].mobility.initFromDisplayString = false

**.ue[*].mobility.constraintAreaMinX = 10m
**.ue[*].mobility.constraintAreaMaxX = 700m
**.ue[*].mobility.constraintAreaMinY = 10m
**.ue[*].mobility.constraintAreaMaxY = 500m
**.ue[*].mobility.constraintAreaMinZ = 0m
**.ue[*].mobility.constraintAreaMaxZ = 100m
**.ue[*].mobility.initialX = uniform(this.constraintAreaMinX, this.constraintAreaMaxX)
**.ue[*].mobility.initialY = uniform(this.constraintAreaMinX, this.constraintAreaMaxX)
**.ue[*].mobility.speed = exponential(10mps)

#------------gNodeB config---------------
*.gNodeB1.mobility.initFromDisplayString = false
*.gNodeB1.mobility.initialX = 400m
*.gNodeB1.mobility.initialY = 250m
*.gNodeB1.mobility.initialZ = 0m


#------------MecHost config---------------
*.mecHost.mobility.initFromDisplayString = false
*.mecHost.mobility.typename = "StationaryMobility"

**.mecHost.mobility.initialX = 400m
**.mecHost.mobility.initialY = 200m

# ----------------------------------------------------------------------------- ## Config "StationaryMobility"
