[General]
### multiCell_mobileMecHost scenario ###
network = simu5g.simulations.NR.mec.appMigration_mobileMECHost.appMigration_mobileMECHost
cmdenv-autoflush = true

result-dir = results
# result-dir = /mnt/data-hdd/veronica/app_migration/results
**.routingRecorder.enabled = false

##########################################################
#            Output Format Results                       #
##########################################################
num-rngs = 3
repeat = 5
seed-set = ${repetition}
output-scalar-file = ${resultdir}/${configname}/${configname}-${iterationvarsf}${repetition}.sca
output-vector-file = ${resultdir}/${configname}/${configname}-${iterationvarsf}${repetition}.vec

**.sctp.**.scalar-recording = false  # remove annoying statistics from SCTP
**.sctp.**.vector-recording = false  # remove annoying statistics from SCTP

#**.responseTime:vector.vector-recording = true
#**.avgServedBlocks*l:vector.vector-recording = true
#**.nrPhy.averageCqi*l:vector.vector-recording = true
#**.*LinkTime:vector.vector-recording = true
#**.nrRlc.um.rlcDelay*l:vector.vector-recording = true

**.scalar-recording = false
**.vector-recording = false


############### SCTP configuration ##################
**.sctp.nagleEnabled = false         # if true, transmission of small packets will be delayed on the X2
**.sctp.enableHeartbeats = false

**.tcp.nagleEnabled = false


##########################################################
#            Simulation parameters                       #
##########################################################
debug-on-errors = false
print-undisposed = true

sim-time-limit = 50s
warmup-period = 0s

*.playgroundSizeX = 2500m
*.playgroundSizeY = 2500m
*.playgroundSizeZ = 50m


############### IPv4 configurator config #################
#**.routingTable.netmaskRoutes = ""
#**.configurator.addSubnetRoutes = false
#**.configurator.addDefaultRoutes = false
*.configurator.config = xmldoc("./demo.xml")
**.configurator.dumpRoutes = true


##########################################################
#              NR specific parameters                   #
##########################################################
############### General PHY parameters ##############
*.gnb*.cellInfo.broadcastMessageInterval = 0.5s
**.fbPeriod = 40tti   # reports CQI every 40ms
**.amcType = "NRAmc"
**.pilotMode = "STDDEV_CQI"
**.targetBler = 0.001
**.blerShift = 5
**.fading = false

#**.downlink_interference = true
#**.uplink_interference = true
#**.ueTxPower = 26dBm
#**.eNodeBTxPower = 46dBm

# ----------------------------------------------------------------------------- #

#######################################################
#        CA and channel model configuration           #
#######################################################
*.carrierAggregation.numComponentCarriers = 1
#*.carrierAggregation.componentCarrier[0].carrierFrequency = 2GHz
*.carrierAggregation.componentCarrier[0].numBands = ${rbs=13}
*.carrierAggregation.componentCarrier[0].numerologyIndex = ${u=2}

*.*.cellularNic.LteChannelModelType = "NRChannelModel"
*.gnb*.cellularNic.numCarriers = 1
*.gnb*.cellularNic.channelModel[0].componentCarrierModule = "carrierAggregation.componentCarrier[0]"

*.ue[*].cellularNic.numCarriers = 1
*.ue[*].cellularNic.nrChannelModel[0].componentCarrierModule = "carrierAggregation.componentCarrier[0]"

*.mobileMecHost*.cellularNic.numCarriers = 1
*.mobileMecHost*.cellularNic.nrChannelModel[0].componentCarrierModule = "carrierAggregation.componentCarrier[0]"

################# X2 configuration #################                                     
*.gnb*.numX2Apps = 1                                        # one x2App per peering node
*.gnb*.x2App[*].server.localPort = 5000 + ancestorIndex(1)  # Server ports (x2App[0]=5000, x2App[1]=5001, ...)

*.gnb1.x2App[0].client.connectAddress = "gnb2%x2ppp0"
*.gnb2.x2App[0].client.connectAddress = "gnb1%x2ppp0"


############### Internet Cloud configuration ##############

**.internet.ipv4Delayer.rng-0 = 1
**.internet.ipv4Delayer.config = xmldoc("internetCloud.xml")

##########################################################
#                      Mobility                          #
##########################################################
**.mobility.constraintAreaMinZ = 0m
**.mobility.constraintAreaMaxZ = 0m

#------------UE config---------------
**.numUes =  5 #${numUEs=10, 20, 30}	#5..30 step 5}

**.ue[*].mobility.initFromDisplayString = false
**.ue[*].mobility.typename = "RandomWaypointMobility"
**.ue[*].mobility.updateInterval = 0.05s

# UE mobility limited in a rectangular area inside the coverage area of the gNodeB
**.ue[*].mobility.constraintAreaMinX = 425m 
**.ue[*].mobility.constraintAreaMaxX = 675m 
**.ue[*].mobility.constraintAreaMinY = 233m 
**.ue[*].mobility.constraintAreaMaxY = 667m 
**.ue[*].mobility.constraintAreaMinZ = 0m
**.ue[*].mobility.constraintAreaMaxZ = 0m

**.ue[*].mobility.initialX = uniform(this.constraintAreaMinX, this.constraintAreaMaxX)
**.ue[*].mobility.initialY = uniform(this.constraintAreaMinY, this.constraintAreaMaxY)
**.ue[*].mobility.speed = exponential(10mps)

**.ue[*].masterId = 0
**.ue[*].macCellId = 0
**.ue[*].nrMasterId = 1
**.ue[*].nrMacCellId = 1
**.dynamicCellAssociation = true
**.enableHandover = true

#------------gNodeB config---------------
**.gnb*.mobility.initFromDisplayString = false

**.gnb1.mobility.initialX = 550m
**.gnb1.mobility.initialY = 450m
**.gnb1.mobility.initialZ = 0m

**.gnb2.mobility.initialX = 1050m
**.gnb2.mobility.initialY = 450m
**.gnb2.mobility.initialZ = 0m

**.gnb*.cellularNic.bgTrafficGenerator[*].numBgUes = 0 #${gnbBgUes=0, 40, 100}	#..80 step 40}

**.gnb*.cellularNic.bgTrafficGenerator[*].bgUE[*].generator.typename = "TrafficGeneratorCbr"
**.gnb*.cellularNic.bgTrafficGenerator[*].bgUE[*].generator.startTimeDl = uniform(0ms, 20ms)
**.gnb*.cellularNic.bgTrafficGenerator[*].bgUE[*].generator.packetSizeDl = ${pktSize}
**.gnb*.cellularNic.bgTrafficGenerator[*].bgUE[*].generator.periodDl = 20ms

**.gnb*.cellularNic.bgTrafficGenerator[*].bgUE[*].generator.startTimeUl = uniform(0ms, 20ms)
**.gnb*.cellularNic.bgTrafficGenerator[*].bgUE[*].generator.packetSizeUl = ${pktSize}
**.gnb*.cellularNic.bgTrafficGenerator[*].bgUE[*].generator.periodUl = 20ms

# ----------------------------------- #
**.gnb*.cellularNic.bgTrafficGenerator[*].bgUE[*].generator.rtxRateDl = 0
**.gnb*.cellularNic.bgTrafficGenerator[*].bgUE[*].generator.rtxRateUl = 0
**.gnb*.cellularNic.bgTrafficGenerator[*].bgUE[*].generator.cqiMeanDl = uniform(5, 13)
**.gnb*.cellularNic.bgTrafficGenerator[*].bgUE[*].generator.cqiStddevDl = 0
**.gnb*.cellularNic.bgTrafficGenerator[*].bgUE[*].generator.cqiMeanUl = uniform(5, 13)
**.gnb*.cellularNic.bgTrafficGenerator[*].bgUE[*].generator.cqiStddevUl = 0

**.gnb1.macCellId = 1   
**.gnb1.macNodeId = 1   
**.gnb2.macCellId = 2   
**.gnb2.macNodeId = 2

#------------mobileMEcHost config---------------
**.mobileMecHost*.masterId = 0
**.mobileMecHost*.macCellId = 0
**.mobileMecHost*.nrMasterId = 1
**.mobileMecHost*.nrMacCellId = 1

**.mobileMecHost*.isMobile = true

**.mobileMecHost*.mobility.initFromDisplayString = false

**.mobileMecHost2.mobility.typename = "StationaryMobility"
**.mobileMecHost2.mobility.initialX = 500m
**.mobileMecHost2.mobility.initialY = 450m

**.mobileMecHost1.mobility.typename = "LinearMobility"
**.mobileMecHost1.mobility.updateInterval = 0.03s

**.mobileMecHost1.mobility.initialX = 550m
**.mobileMecHost1.mobility.initialY = 500m
**.mobileMecHost1.mobility.initialMovementHeading = 0deg
**.mobileMecHost1.mobility.speed = 10mps


#------------Background Cells config---------------
*.numBgCells = ${numBgCells=6}
*.bgCell[*].mobility.initFromDisplayString = false

*.bgCell[*].bgTrafficGenerator.numBgUes = 30

*.bgCell[0].mobility.initialX = 300m
*.bgCell[0].mobility.initialY = 17m
*.bgCell[1].mobility.initialX = 800m
*.bgCell[1].mobility.initialY = 17m
*.bgCell[2].mobility.initialX = 1300m
*.bgCell[2].mobility.initialY = 17m

*.bgCell[3].mobility.initialX = 300m
*.bgCell[3].mobility.initialY = 883m
*.bgCell[4].mobility.initialX = 800m
*.bgCell[4].mobility.initialY = 883m
*.bgCell[5].mobility.initialX = 1300m
*.bgCell[5].mobility.initialY = 883m

### bg left and right cells - if added
#*.bgCell[6].mobility.initialX = 50m
#*.bgCell[6].mobility.initialY = 450m
#*.bgCell[7].mobility.initialX = 1550m
#*.bgCell[7].mobility.initialY = 450m

*.bgCell[*].bgScheduler.isNr = true
*.bgCell[*].bgScheduler.numBands = ${rbs}
*.bgCell[*].bgScheduler.numerologyIndex = ${u}
#*.bgCell[*].bgScheduler.txPower = ${bgTxPwr=23dBm}

# position of background UEs in the background cells
*.bgCell[*].bgTrafficGenerator.bgUE[*].mobility.typename = "RandomWaypointMobility"
*.bgCell[*].bgTrafficGenerator.bgUE[*].mobility.initFromDisplayString = false

**.bgCell[*].bgTrafficGenerator.bgUE[*].mobility.constraintAreaMaxX = 2500m
**.bgCell[*].bgTrafficGenerator.bgUE[*].mobility.constraintAreaMaxY = 2500m
**.bgCell[*].bgTrafficGenerator.bgUE[*].mobility.constraintAreaMinX = -500m
**.bgCell[*].bgTrafficGenerator.bgUE[*].mobility.constraintAreaMinY = -500m

*.bgCell[0].bgTrafficGenerator.bgUE[*].mobility.initialX = uniform(50m,550m)
*.bgCell[0].bgTrafficGenerator.bgUE[*].mobility.initialY = uniform(-233m,267m)
*.bgCell[1].bgTrafficGenerator.bgUE[*].mobility.initialX = uniform(550m,1050m)
*.bgCell[1].bgTrafficGenerator.bgUE[*].mobility.initialY = uniform(-233m,267m)
*.bgCell[2].bgTrafficGenerator.bgUE[*].mobility.initialX = uniform(1050m,1550m)
*.bgCell[2].bgTrafficGenerator.bgUE[*].mobility.initialY = uniform(550m,1050m)

*.bgCell[3].bgTrafficGenerator.bgUE[*].mobility.initialX = uniform(50m,550m)
*.bgCell[3].bgTrafficGenerator.bgUE[*].mobility.initialY = uniform(633m,1133m)
*.bgCell[4].bgTrafficGenerator.bgUE[*].mobility.initialX = uniform(550m,1050m)
*.bgCell[4].bgTrafficGenerator.bgUE[*].mobility.initialY = uniform(633m,1133m)
*.bgCell[5].bgTrafficGenerator.bgUE[*].mobility.initialX = uniform(1050m,1550m)
*.bgCell[5].bgTrafficGenerator.bgUE[*].mobility.initialY = uniform(633m,1133m)

### bg cell right and left - if added
#*.bgCell[6].bgTrafficGenerator.bgUE[*].mobility.initialX = uniform(-300m,200m)
#*.bgCell[6].bgTrafficGenerator.bgUE[*].mobility.initialY = uniform(200m,700m)
#*.bgCell[7].bgTrafficGenerator.bgUE[*].mobility.initialX = uniform(1200m,1700m)
#*.bgCell[7].bgTrafficGenerator.bgUE[*].mobility.initialY = uniform(200m,700m)

*.bgCell[*].bgTrafficGenerator.bgUE[*].mobility.speed = exponential(10mps)


**.hasRNISupport = true

# tcp settings
**.tcp.typename = "Tcp"
**.tcp.advertisedWindow = 65535         # in bytes, corresponds with the maximal receiver buffer capacity (Note: normally, NIC queues should be at least this size)
**.tcp.tcpAlgorithmClass = "TcpReno"    # TcpReno/TcpTahoe/TcpNewReno/TcpNoCongestionControl/DumbTcp
**.tcp.sackSupport = true               # Selective Acknowledgment (RFC 2018, 2883, 3517) support (header option) (SACK will be enabled for a connection if both endpoints support it)

##########################################################
#                    App Layer                           #
##########################################################

#########################_UE Side_#######################

#------------UERequestApp---------------
*.ue[*].numApps = 2
*.ue[*].app[0].typename = "DeviceApp"
*.ue[*].app[0].localPort = 4500
*.ue[*].app[0].ualcmpAddress = "ualcmp"
*.ue[*].app[0].ualcmpDestPort = 1000
*.ue[*].app[0].appPackageSource = "ApplicationDescriptors/ResponseCbrApp.json"

*.ue[*].app[1].typename = "UERequestCbrApp"
*.ue[*].app[1].deviceAppAddress = "ue["+string(ancestorIndex(1))+"]"
*.ue[*].app[1].deviceAppPort = 4500
*.ue[*].app[1].startTime = uniform(1s, 5s)										#when sending start request app									#period to sending messages
*.ue[*].app[1].stopTime = 250s

# packet size / send interval
*.ue[*].app[1].requestPacketSize = ${pktSize=500B}
*.ue[*].app[1].period = 20ms

### MEC Response App
**.responsePacketSize = ${pktSize}										#when sending stop MEC response app

#----------------------------------------

######################_ME Host Side_#####################

# resources available
*.mobileMecHost*.maxMECApps = 100										#max ME Apps to instantiate
*.mobileMecHost*.maxRam = 32GB											#max KBytes of Ram Space
*.mobileMecHost*.maxDisk = 100TB											#max KBytes of Ram Space
*.mobileMecHost*.maxCpuSpeed = 400000									#max percentage of CPU
#----------------------------------------

*.mobileMecHost1.bsList = ["gnb1", "gnb2"]
*.mobileMecHost2.bsList = ["gnb1"]
*.mobileMecHost*.mecPlatformManager.mecOrchestrator = "mecOrchestrator.mecOrchestratorApp"

#-------ETSI MEC Services:---------------
### mobile MEC host 1
*.mobileMecHost1.mecPlatform.numMecServices = 1
*.mobileMecHost1.mecPlatform.mecService[0].typename = "RNIService"
*.mobileMecHost1.mecPlatform.mecService[0].localAddress = "mobileMecHost1"
*.mobileMecHost1.mecPlatform.mecService[0].localPort = 10020

*.mobileMecHost1.mecPlatform.mecService[0].rng-0 = 0 # request service time
*.mobileMecHost1.mecPlatform.mecService[0].rng-1 = 1 # subscription service time
*.mobileMecHost1.mecPlatform.mecService[0].requestServiceTime = 100us
*.mobileMecHost*.mecPlatform.mecService[0].subscriptionServiceTime = 11us

*.mobileMecHost1.mecPlatform.serviceRegistry.localAddress = "mobileMecHost1"
*.mobileMecHost1.mecPlatform.serviceRegistry.localPort = 10021

*.mobileMecHost1.mecPlatform.serviceRegistry.rng-0 = 0 # request service time
*.mobileMecHost1.mecPlatform.serviceRegistry.rng-1 = 1 # subscription service time

### mobile MEC host 2
*.mobileMecHost2.mecPlatform.numMecServices = 1
*.mobileMecHost2.mecPlatform.mecService[0].typename = "RNIService"
*.mobileMecHost2.mecPlatform.mecService[0].localAddress = "mobileMecHost2"
*.mobileMecHost2.mecPlatform.mecService[0].localPort = 10020

*.mobileMecHost2.mecPlatform.mecService[0].rng-0 = 0 # request service time
*.mobileMecHost2.mecPlatform.mecService[0].rng-1 = 1 # subscription service time
*.mobileMecHost2.mecPlatform.mecService[0].requestServiceTime = 100us
*.mobileMecHost2.mecPlatform.mecService[0].subscriptionServiceTime = 11us

*.mobileMecHost2.mecPlatform.serviceRegistry.localAddress = "mobileMecHost2"
*.mobileMecHost2.mecPlatform.serviceRegistry.localPort = 10021

*.mobileMecHost2.mecPlatform.serviceRegistry.rng-0 = 0 # request service time
*.mobileMecHost2.mecPlatform.serviceRegistry.rng-1 = 1 # subscription service time


#------- MEC orchestrator---------------
**.mecOrchestrator.mecHostList = ["mobileMecHost1", "mobileMecHost2"]
**.mecOrchestrator.mecApplicationPackageList = ["ResponseCbrApp"]   # List of MEC app descriptors to be onboarded at
**.mecOrchestrator.selectionPolicy = "MigrationSelectionBased"
**.mecOrchestrator.onboardingTime = 20ms
**.mecOrchestrator.instantiationTime = 20ms


#------- UALCPM ---------------
**.ualcmp.mecOrchestratorHostname = "mecOrchestrator.mecOrchestratorApp"


######### CQI and HARQ parameters for background UEs

#------------CQI-------------
**.useProbabilisticCqi = true

*.bgCell[*].bgTrafficGenerator.bgUE[*].generator.typename = "TrafficGeneratorCbr"
*.bgCell[*].bgTrafficGenerator.bgUE[*].generator.startTimeDl = uniform(0ms, 20ms)
*.bgCell[*].bgTrafficGenerator.bgUE[*].generator.packetSizeDl = ${pktSize}
*.bgCell[*].bgTrafficGenerator.bgUE[*].generator.periodDl = 20ms

*.bgCell[*].bgTrafficGenerator.bgUE[*].generator.startTimeUl = uniform(0ms, 20ms)
*.bgCell[*].bgTrafficGenerator.bgUE[*].generator.packetSizeUl = ${pktSize}
*.bgCell[*].bgTrafficGenerator.bgUE[*].generator.periodUl = 20ms

# ----------------------------------- #
*.bgCell[*].bgTrafficGenerator.bgUE[*].generator.rtxRateDl = 0
*.bgCell[*].bgTrafficGenerator.bgUE[*].generator.rtxRateUl = 0
*.bgCell[*].bgTrafficGenerator.bgUE[*].generator.cqiMeanDl = uniform(5, 13)
*.bgCell[*].bgTrafficGenerator.bgUE[*].generator.cqiStddevDl = 0
*.bgCell[*].bgTrafficGenerator.bgUE[*].generator.cqiMeanUl = uniform(5, 13)
*.bgCell[*].bgTrafficGenerator.bgUE[*].generator.cqiStddevUl = 0

#------------------------------------------------------------------------------#


# ############################################################################## #

# Config
# Benchmark configuration with a standard mecHost moving linearly in the network 
# and connecting to different gnb through handover procedure but no app migration is performed
[Config handover_no_migration]
 
**.mobileMecHost*.isMobilityAware = false


# Configuration with a mobile Mec Host moving linearly in the network
# performing handover and app migration

[Config handover_with_migration]

**.mobileMecHost1.isMobilityAware = true


# Configuration with a mobile Mec Host moving linearly in the network
# performing handover and app migration and the target mec host far from gnb

[Config migration_with_distant_target]
extends = handover_with_migration

**.mobileMecHost2.mobility.typename = "StationaryMobility"
**.mobileMecHost2.mobility.initialX = 350m
**.mobileMecHost2.mobility.initialY = 650m

[Config migration_with_random_target_position]
extends = handover_with_migration

# mobileMecHost2 mobility limited in a rectangular area inside the coverage area of the gNodeB
**.mobileMecHost2.mobility.constraintAreaMinX = 425m
**.mobileMecHost2.mobility.constraintAreaMaxX = 675m
**.mobileMecHost2.mobility.constraintAreaMinY = 233m
**.mobileMecHost2.mobility.constraintAreaMaxY = 667m
**.mobileMecHost2.mobility.constraintAreaMinZ = 0m
**.mobileMecHost2.mobility.constraintAreaMaxZ = 0m

**.mobileMecHost2.mobility.initFromDisplayString = false
**.mobileMecHost2.mobility.typename = "RandomWaypointMobility"
**.mobileMecHost2.mobility.updateInterval = 0.05s

**.mobileMecHost2.mobility.initialX = uniform(this.constraintAreaMinX, this.constraintAreaMaxX)
**.mobileMecHost2.mobility.initialY = uniform(this.constraintAreaMinY, this.constraintAreaMaxY)
**.mobileMecHost2.mobility.speed = exponential(10mps)


# ----------------------------------------------------------------------------- #
